/// Flutter icons SendMessage
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SendMessage
///      fonts:
///       - asset: fonts/SendMessage.ttf
///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class SendMessage {
  SendMessage._();

  static const _kFontFam = 'SendMessage';
  static const _kFontPkg = null;

  static const IconData direction = IconData(0xf124, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
